
name: 'dbt_real_estate_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_real_estate_project' # Trebuie să corespundă cu profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

#materializarea default și schemele pentru diferite subdirectoare
models:
  dbt_real_estate_project:
    staging:
      +schema: RAW_STAGING
      +materialized: view
      elementix:
        +tags: "elementix_source"

    intermediate:
      +schema: RAW_STAGING 
      +materialized: ephemeral
      elementix:
        +tags: "elementix_int"


    marts:
      +schema: ANALYTICS
      +materialized: table
      elementix:
        +tags: "elementix_mart"
